/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OB.CheckValid;

/**
 *
 * @author MyLaptop
 */
public class StudentFrameForm extends javax.swing.JFrame {

   CheckValid check = new CheckValid();

    /**
     * Creates new form StudentFrameForm
     */
    public StudentFrameForm() {
//        Date date = new Date();
        initComponents();
        jTextFieldCode.setColumns(10);
        setLocationRelativeTo(null);
//        System.out.println(date.getMonth());
//        System.out.println(date.getDay());
//        System.out.println(date.getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCode = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelHint = new javax.swing.JLabel();
        jLabelNoti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(499, 342));
        getContentPane().setLayout(null);

        jLabelCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode.setText("Student Code:");
        getContentPane().add(jLabelCode);
        jLabelCode.setBounds(50, 50, 110, 17);

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelName.setText("Student Name:");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(50, 90, 110, 17);

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDate.setText("Birth Date:");
        getContentPane().add(jLabelDate);
        jLabelDate.setBounds(50, 130, 90, 17);

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPhone.setText("Phone Number:");
        getContentPane().add(jLabelPhone);
        jLabelPhone.setBounds(50, 170, 110, 17);

        jLabelMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMail.setText("Email:");
        getContentPane().add(jLabelMail);
        jLabelMail.setBounds(50, 210, 41, 17);

        jTextFieldCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodeFocusLost(evt);
            }
        });
        jTextFieldCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodeKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCode);
        jTextFieldCode.setBounds(190, 50, 150, 30);

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(190, 90, 230, 30);

        jTextFieldDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldDate);
        jTextFieldDate.setBounds(190, 130, 150, 30);

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneFocusLost(evt);
            }
        });
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPhone);
        jTextFieldPhone.setBounds(190, 170, 150, 30);

        jTextFieldMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMailFocusLost(evt);
            }
        });
        jTextFieldMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMailKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldMail);
        jTextFieldMail.setBounds(190, 210, 230, 30);

        jLabelHint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHint.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabelHint);
        jLabelHint.setBounds(360, 130, 100, 30);

        jLabelNoti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNoti.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabelNoti);
        jLabelNoti.setBounds(40, 260, 410, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodeFocusLost
        // TODO add your handling code here:
        if (jTextFieldCode.getText().equals("")) {
            jLabelNoti.setText("Please enter student code");
        } else if (!check.ckCharCode(jTextFieldCode.getText())) {
            jLabelNoti.setText("Student code not contains special characters: @, #, $ and space");
        } else {
            jLabelNoti.setText("Code is valid");
        }
    }//GEN-LAST:event_jTextFieldCodeFocusLost

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        // TODO add your handling code here:
        if (jTextFieldName.getText().equals("")) {
            jLabelNoti.setText("Please enter Student name");
        }else if (!check.ckValidName(jTextFieldName.getText())) {
            jLabelNoti.setText("Name not be number and special characters");
        } else {
            jLabelNoti.setText("Name is valid");
        }
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        // TODO add your handling code here:
        jLabelHint.setText("");
        if (jTextFieldDate.getText().equals("")) {
            jLabelNoti.setText("Please enter Birth date");
        } else if (!check.ckValidBirthDate(jTextFieldDate.getText())) {
            jLabelNoti.setText("Birth date must be in format MM/DD/YYYY");
        } else if (!check.ckDateIsExist(jTextFieldDate.getText())) {
            jLabelNoti.setText("This date isn't exsit.");
        } else if (!check.ckBirthDate(jTextFieldDate.getText())) {
            jLabelNoti.setText("Invalid birth date");
        } else {
            jLabelNoti.setText("Date is valid");
        }
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneFocusLost
        // TODO add your handling code here:
        if (jTextFieldPhone.getText().equals("")) {
            jLabelNoti.setText("Please enter phone number");
        } else if (!check.ckValidPhone(jTextFieldPhone.getText())) {
            jLabelNoti.setText("Phone number contains numeric characters only 0 – 9");
        } else {
            jLabelNoti.setText("Phone is valid");
        }
    }//GEN-LAST:event_jTextFieldPhoneFocusLost

    private void jTextFieldMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMailFocusLost
        // TODO add your handling code here:
        if (jTextFieldMail.getText().equals("")) {
            jLabelNoti.setText("Please enter email");
        } else if (!check.ckCharEmail(jTextFieldMail.getText())) {
            jLabelNoti.setText("Email not contains special characters: !, #, $");
        } else if (!check.ckValidEmail(jTextFieldMail.getText())) {
            jLabelNoti.setText("Email contains only one @ character but not first and last");
        } else {
            jLabelNoti.setText("Email is valid");
        }
    }//GEN-LAST:event_jTextFieldMailFocusLost

    private void jTextFieldCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodeKeyTyped
        // TODO add your handling code here:
        if (jTextFieldCode.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodeKeyTyped

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        // TODO add your handling code here:
        if (jTextFieldName.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
        jLabelHint.setText("MM/DD/YYYY");
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        // TODO add your handling code here:
        if (jTextFieldPhone.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped

    private void jTextFieldMailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMailKeyTyped
        // TODO add your handling code here:
        if (jTextFieldMail.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNoti;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
